import type { AdminGuideTopic } from "./document-guide";

type EnglishTopic = Pick<AdminGuideTopic, "title" | "group" | "purpose" | "steps" | "result" | "notes"> &
  Partial<Pick<AdminGuideTopic, "prerequisites">>;

export const adminGuideEnglish: Record<AdminGuideTopic["id"], EnglishTopic> = {
  dashboard: {
    title: "Dashboard and custom dashboards", group: "Overview and administration",
    purpose: "Review operational metrics and add built-in widgets to your personal dashboard; it does not support arbitrary queries or charts.",
    steps: ["Open Dashboard and check the date range and scope for each metric.", "Select Customize dashboard; choose a Metric in the inline builder and enter an optional Title.", "Select Add widget to save it automatically; use the remove icon on a card to delete a widget.", "Compare each metric with its detail page; widgets cannot be dragged or rearranged."],
    result: "The layout is saved to the Admin account and follows it across devices. Widgets do not replace the Ledger or detailed reports.",
    notes: ["Dashboard contents may vary by data and permissions.", "If a total looks unexpected, check the metric definition, date range, point type, and transaction status."],
  },
  "roles-permissions": {
    title: "Roles & permissions", group: "Overview and administration",
    purpose: "Create custom admin roles and assign permissions by feature so each administrator has only the access needed for their work.",
    prerequisites: "You need permission-management access. Admin sign-in access and feature-level capabilities are checked separately.",
    steps: ["Open Roles & permissions and select a role to inspect or edit.", "Create a role with a name that describes its responsibility, such as Campaign approver.", "Open each taskbar-style feature group and enable the required view or manage capabilities.", "Save the role, assign it to the appropriate admin account, and verify access with a least-privileged account."],
    result: "Menus and actions are controlled by the role's capabilities. Changes may apply immediately or after the session is refreshed.",
    notes: ["Grant only the minimum access required; manage permissions usually allow data changes.", "Do not remove or downgrade the last administrator before confirming another administrator can manage the system."],
  },
  members: {
    title: "Members and member profiles", group: "Members and data",
    purpose: "Find members, review profiles and status, inspect wallets and history, and use custom fields to store segmentation data.",
    steps: ["Search by name, email, or member ID; use filters to narrow the list.", "Open a member profile to review personal details, custom fields, wallets, and transactions.", "Select Edit to change permitted fields, save, and review history if needed.", "To stop an account, use Deactivate according to your internal process. Use Delete only after reviewing its consequences."],
    result: "Profile changes are saved. Depending on the action, administrative changes may appear in Logs or the Ledger.",
    notes: ["Deactivation preserves history but clears the current balance; reactivation does not restore the cleared balance.", "Deletion removes the active member and clears wallet balances, while existing transaction history remains.", "Email is not guaranteed to be unique at the data layer. Use memberId to identify a specific record."],
  },
  "member-fields": {
    title: "Member fields", group: "Members and data",
    purpose: "Create additional member attributes such as birth date, department, or an internal code. Supported fields can be used in segments and events.",
    steps: ["Open Member fields and create a field with a display name, stable key, and suitable data type.", "Set whether the field is required and configure type-specific options.", "Save it, then populate it in member profiles or import files.", "Use the field in Rule Builder or an event if that data type is supported."],
    result: "The new field appears on screens designed to use custom member fields.",
    notes: ["Use the Date type for dates used by filters or triggers; do not store dates as arbitrary text.", "Changing a key after data exists can break conditions that rely on it. Prefer creating a new key."],
  },
  "member-import": {
    title: "Import or bulk-update members", group: "Members and data",
    purpose: "Create members or update profiles and balances from a file, while choosing which fields should be imported.",
    prerequisites: "Prepare a CSV, XLSX, or JSON file with clear headers. Back up important data before a large update.",
    steps: ["Open Member import and download the sample file or select your data file.", "Choose the fields to import. Mandatory fields are selected by default and cannot be deselected.", "Review header detection, column mapping, date/point formats, and create-versus-update mode.", "Editable import preview lets you edit the parsed file contents; it is not a dry run or validation step.", "Select Import members only when ready to write data; the action commits immediately. Review its success/failure summary and spot-check several member records."],
    result: "Email is required to create a member; memberId can identify a record for updates. Unselected fields are not written from the file.",
    notes: ["balance_CODE columns set the target balance; point_CODE columns add or subtract transactions. Do not interchange these conventions.", "If status is omitted, the import normally does not request a status change. Fix missing headers or unknown point types before rerunning.", "Point imports can change real balances. Start with a small group and reconcile the Ledger before a large import."],
  },
  "point-types": {
    title: "Point type registry and expiry", group: "Points, wallets, and ledger",
    purpose: "Define point types, customer visibility, and permitted operations such as issuance, transfers, reward redemption, exchange, expiry, and bank usage.",
    steps: ["Open Point type registry and select a type to edit, or create a new one.", "Set its name, code, unit, and status; configure customer visibility.", "Choose the expiry policy and permitted transfer or redemption operations.", "If transfers are allowed, configure the explicit source-to-destination matrix, conversion ratio, and limits.", "Save, then verify the type in a campaign, wallet adjustment, or customer portal as appropriate."],
    result: "Point types underpin balances, transactions, and issuance. A transfer destination is unavailable unless explicitly configured.",
    notes: ["AFTER_DAYS is measured from point-type creation, not from each grant; FIXED_DATE uses one shared date; PER_GRANT sets expiry per grant; NEVER has no expiry.", "New grants may be invalid if the configured expiry date has already passed.", "Review the impact on existing balances before changing an expiry policy."],
  },
  "wallet-adjustments": {
    title: "Wallet adjustments", group: "Points, wallets, and ledger",
    purpose: "Adjust a member's points with a reason to correct an error or record an authorized administrative action.",
    prerequisites: "You need wallet-management permission. Verify the member and point type before confirming.",
    steps: ["Open Wallet adjustments, find the member, and select the correct point type.", "Choose Add or Remove, enter a whole-point amount, and provide a clear reason.", "Review the confirmation. Add may require available bank value; Remove returns points to the admin bank according to the current rules.", "Confirm, then search the Ledger by member, actor, or date."],
    result: "The member balance and Ledger are updated with the reason recorded as an administrative transaction.",
    notes: ["Do not use an adjustment instead of a campaign when audience, event, claim, or campaign reporting is required.", "Check the sign and point type carefully; an adjustment can immediately affect spendable points."],
  },
  "issuance-rules": {
    title: "Point issuance", group: "Points, wallets, and ledger",
    purpose: "This is a guide and entry point for issuance configuration. Events define when something happens; campaigns define the audience, points, and approval policy.",
    steps: ["Open Point issuance to distinguish standing campaigns for regular occasions from Approval required campaigns for exceptions.", "Select Open campaign builder to configure audience, event/trigger, point type, award, claim/auto mode, and budget.", "If you need a new event, open Configure event definitions, create its occurrence, then select it in the campaign.", "For an exceptional campaign, select Approval required, add a justification, and submit it. Save or activate standing campaigns through their normal flow."],
    result: "This page does not create an independent issuance rule; automation is configured through Event definition + Campaign.",
    notes: ["Campaign approval covers the configuration, audience, schedule, and budget. It is different from a one-member grant proposal.", "Draft and pending-approval campaigns do not issue points."],
  },
  "banks-cycles": {
    title: "Banks and bank cycles", group: "Points, wallets, and ledger",
    purpose: "Manage the central point bank, funding transactions, and allocation windows. Closing a cycle does not delete unused bank value.",
    steps: ["Select a point type and review its current bank balance.", "To fund the bank, enter an amount and reason to create a funding record.", "Open a cycle with its date range or note, then monitor opening value, transactions, and allocation.", "When closing the cycle, provide a closing reason and confirm the responsible administrator.", "Open the cycle details to review its transactions and closing balance; unused value remains in the bank."],
    result: "A closed cycle records its actor, timestamps, reason, and transaction history. Allocated is net of qualifying returns or refunds.",
    notes: ["Wallet removals and project returns may return points to the bank/cycle depending on transaction type.", "Use net allocated, not gross issuance, when reconciling a cycle.", "Bank funding is a bank transaction, not a member-wallet transaction."],
  },
  ledger: {
    title: "Ledger and bank funding history", group: "Points, wallets, and ledger",
    purpose: "Reconcile point transactions and central funding: who acted, which member was affected, the source/reason, and the resulting balance.",
    steps: ["Open Ledger and choose the transaction group or bank-funding filter.", "Filter by date, actor/action, member/email, point type, or cycle.", "Review actor, action type, target member, source, reason, amount, resulting balance, and timestamp.", "Open a row for business metadata. Use Data export if you need a report file."],
    result: "The Ledger explains point movements. Logs focus on in-app actions and audit payloads.",
    notes: ["Member email helps identify a recipient, but also verify memberId if emails may be duplicated.", "A bank-funding row without a target member is a central-fund transaction, not necessarily missing member data."],
  },
  segments: {
    title: "Segments: group members", group: "Segmentation and achievements",
    purpose: "Build a dynamic group from member conditions or a static group selected by an administrator. Campaigns and tiers can use segments where supported.",
    steps: ["Open Segments and choose a dynamic or static segment.", "For a dynamic segment, add supported member, balance, or event conditions and choose AND or OR logic.", "Review the estimated member count, save, and inspect the matching member list.", "For a static segment, search and select members individually or select all matching results, then save."],
    result: "Dynamic membership is recalculated from data; static membership retains the selected member list.",
    notes: ["Check timezone, date, and data type when using date conditions.", "Review the member list before attaching a segment to a point-issuing campaign."],
  },
  "recognition-categories": {
    title: "Recognition categories", group: "Segmentation and achievements",
    purpose: "Manage the categories members can choose when sending recognition, giving point transfers useful context for reporting.",
    steps: ["Open Recognition categories under Automation & governance.", "Create a category name and label, and activate it if members should be able to select it.", "Save and verify it in Give Recognition in the customer portal."],
    result: "Active categories appear in recognition. Inactive categories should not be used for new transfers.",
    notes: ["A category classifies the reason; it does not change transfer permissions or conversion rates.", "Use clear labels so members and reviewers interpret the category consistently."],
  },
  "tiers-badges": {
    title: "Tiers and Badges", group: "Segmentation and achievements",
    purpose: "Tiers represent levels based on one or more point thresholds; badges represent separate achievements or conditions.",
    steps: ["For a tier, set its name, color, order, and one or more thresholds by point type.", "Choose AND when all requirements must be met, or OR when meeting any one requirement is sufficient.", "For a badge, open Badges, create a badge, add a description/image and conditions, and choose AND/OR logic.", "Save and check the customer view with a member who should qualify and one who should not."],
    result: "Customers see their tier and progress based on configured requirements. Eligible badges are automatic unless set up for manual award.",
    notes: ["A badge is not a reward or point grant unless that benefit is configured separately.", "Verify point units and AND/OR logic before activation."],
  },
  events: {
    title: "Event definitions", group: "Automation, campaigns, and approvals",
    purpose: "Define when an event occurs so campaigns can run automatically, for example on registration, a member date, a fixed date, check-in, manual run, or an integration event.",
    steps: ["Create an event with a unique key, display name, and occurrence type.", "For an annual member date, select a Date custom field or account creation date, then set timezone and any special-date rules.", "For a fixed date, choose a one-time or annual occurrence. For check-in, manual, or external events, review the trigger behavior.", "Save as inactive while checking the configuration; activate only when it is ready.", "Select the active event in a campaign and monitor its issuance status."],
    result: "An active event can trigger linked campaigns. Scheduled events are checked periodically; registration is emitted during member creation; external events must be reported by an integration.",
    notes: ["Creating an external event name does not emit that event by itself.", "Manual is a one-time administrator-triggered run, not a customer check-in button or an integration.", "Inactive events should not be expected to issue campaign rewards."],
  },
  campaigns: {
    title: "Campaigns: automatic issuance or member claim", group: "Automation, campaigns, and approvals",
    purpose: "Create a reward program based on an audience, event, and point type. Campaigns can be standing/default or require approval.",
    steps: ["Select Create campaign. On Occasion, enter the name, choose a trigger event, and select the Standing or Approval required policy; the approval policy requires justification.", "On Recipients, choose the audience/segment.", "On Reward, select the point type and award amount, then choose AUTO issuance or CLAIM by the member; configure usage limits as needed.", "On Schedule, choose automatic execution or a specific date and set the schedule.", "On Review, select Calculate Estimate and recalculate after changing the audience or award. Save as Draft or Submit for approval; create a Standing campaign and activate it from the list when ready.", "Monitor issuance status and member rows; select Refresh for the latest status."],
    result: "AUTO credits the wallet when the event runs; CLAIM creates a pending reward. Approval-required campaigns only run after approval and activation through their configured flow.",
    notes: ["Run campaign now performs issuance or creates claims; it is not a preview. Verify the audience, amount, and status before using it.", "Editing an approved campaign may require approval again.", "Impact estimates depend on the current audience and per-member/budget limits; recalculate after changing settings.", "Do not confuse a blank unlimited budget with a zero-point budget."],
  },
  "workflows-approvals": {
    title: "Workflows and Approval inbox", group: "Automation, campaigns, and approvals",
    purpose: "Workflows route supported requests to user or role approvers. The inbox is where assigned approval requests are processed.",
    steps: ["In Workflows, choose an action key supported by the application and activate the workflow.", "Add approval layers, assign approver users or roles, and configure ANY, ALL, or COUNT rules.", "Save. Only new requests use the currently active workflow.", "In Approval inbox, open a request and review its details and related data. Only the current layer's assignee can decide.", "Approve to proceed, or Reject with a comment; review History after submission."],
    result: "Requests continue through their configured layers or finish as approved/rejected. A requester cannot approve their own request.",
    notes: ["Not every CRUD action has approval; only actions connected to an approval handler create requests.", "Requests keep the workflow/assignee snapshot from submission. Editing a workflow does not reassign an existing request.", "Only an active workflow applies to new requests."],
  },
  "approval-inbox": {
    title: "Approval inbox: review and track requests", group: "Automation, campaigns, and approvals",
    purpose: "Review requests assigned to you at the current approval layer, make a decision, and inspect the approval history.",
    steps: ["Open Approval inbox or select the approval notification you need to handle.", "Open the request and review its action/subject, requester, justification, and details.", "Select Approve to proceed or complete the workflow, or Reject and provide a reason.", "Open History to review each approval step and decision maker."],
    result: "The unread notification badge changes when notifications are marked read. The business request changes only after a decision is successfully submitted.",
    notes: ["Opening a notification does not approve the request.", "Only the approver assigned to the current layer can act; self-approval is not allowed."],
  },
  projects: {
    title: "Group projects: planning, escrow, and awards", group: "Automation, campaigns, and approvals",
    purpose: "A PM proposes a project budget by point type. After plan approval, they invite members, assign tasks, confirm completion, and request point awards for approval.",
    steps: ["Create a project plan with its details, custom fields, and requested budget for each point type.", "Save as Draft or Submit for approval. Address comments/rejection, edit the plan, and resubmit if needed.", "After plan approval, activate the project and invite/enroll members. Members accept invitations when required.", "Create and assign tasks; track them until the required work is done.", "The PM confirms project completion, then enters member awards as amounts or percentages for each point type.", "Submit the award request for approval. Once approved, points are issued from project escrow; closing the project returns the remaining escrow to the bank."],
    result: "Plan approval reserves budget in escrow. Award approval issues from escrow, so it does not debit the bank a second time. A rejected request can be revised and resubmitted.",
    notes: ["Budget and allocation details are restricted to admins/PMs with the relevant access; do not share financial screenshots with members.", "Do not confirm completion while required tasks are unfinished.", "Percentages use the approved budget; point amounts must be valid whole numbers and not exceed available escrow."],
  },
  rewards: {
    title: "Rewards and redemption history", group: "Campaigns, rewards, and exchange",
    purpose: "Create the rewards catalog, set prices by point type, manage stock/eligibility, and review redemption and fulfillment records.",
    steps: ["Create a reward with a name, description, image, category, status, and active dates.", "Set the price for each accepted point type; configure stock or leave it blank if the form defines blank as unlimited.", "Optionally restrict by tier, then check the customer view with members who do and do not qualify.", "Open redemption history to find a member by name/email and review or update fulfillment status."],
    result: "A customer can redeem an active reward when eligible, in stock if limited, and holding enough points.",
    notes: ["Redemption deducts points; fulfillment/delivery may need to be handled separately and may not integrate with an external system.", "Do not enter stock 0 if you intend to make inventory unlimited."],
  },
  coupons: {
    title: "Coupons and batch code generation", group: "Campaigns, rewards, and exchange",
    purpose: "Create and manage batches of coupon codes with a prefix, quantity, and supported usage/display rules.",
    steps: ["Open Coupons or Generate batch.", "Enter the name/prefix, number of codes, limits, and validity dates supported by the form.", "Review the preview and code count before creating the batch.", "Open the batch to inspect status and use the available export actions."],
    result: "Codes are created and managed inside LoyaltyOS. This guide does not assume an external checkout or purchase integration.",
    notes: ["Treat code files as sensitive and share them only with authorized recipients.", "Check start/end dates to prevent codes from being used outside the intended period."],
  },
  exchange: {
    title: "Exchange vouchers", group: "Campaigns, rewards, and exchange",
    purpose: "Manage versioned point-exchange rates and member requests through pending, approved, completed, rejected, or cancelled states.",
    steps: ["Configure a new exchange rate; each saved rate is versioned.", "Open request history, filter by status, and inspect the member, point amount, and rate snapshot.", "Approve or reject according to policy. When the external process is actually complete, select Complete and enter its completion reference.", "Verify the final status and related Ledger/notification records."],
    result: "Each request preserves the exchange-rate snapshot from submission. Rejected or cancelled requests can be refunded through the configured flow.",
    notes: ["An exchange voucher is an internal accounting record; it does not prove that an external payment or transfer occurred.", "Do not complete a request until the actual business process is confirmed and the required reference is available."],
  },
  logs: {
    title: "Logs and audit trail", group: "Reporting and notifications",
    purpose: "Find who performed an action, which feature/action was involved, the actor type, timestamp, and any recorded payload details.",
    steps: ["Open Logs and filter by text, actor, action, actor type, feature, and date range.", "Open a record to inspect its payload; use member, project, or campaign IDs to trace related work.", "For a file, open Data export and choose the audit/log dataset if your role allows it.", "Compare Logs (application actions), Ledger (point changes), and Approval history (decisions)."],
    result: "These sources answer different questions: which action ran, how points changed, and who approved it.",
    notes: ["Not every failed request creates an audit record; check server logs if a transaction did not commit.", "Payloads may contain business data; share only the information needed."],
  },
  "data-export": {
    title: "Data export", group: "Reporting and notifications",
    purpose: "Export selected, human-readable fields from an authorized dataset instead of receiving an opaque JSON dump.",
    steps: ["Choose a dataset such as Members, Ledger, Bank cycles, Campaigns, Events, or approvals.", "Select only the fields you need and review their labels and explanations.", "Apply filters or a scope if available; check the required capability and record count.", "Export CSV and inspect a few rows before sharing the file."],
    result: "The file contains the selected fields and only the records allowed by your access.",
    notes: ["Export only what is necessary; member balances, emails, and audit payloads may be sensitive.", "Passwords, tokens, and session secrets are not included in the export catalog.", "Exports have row/size limits; narrow the filters if the result exceeds them."],
  },
  "notification-templates": {
    title: "Notification templates", group: "Reporting and notifications",
    purpose: "Manage notification content by trigger and channel, edit multiple languages together, and review available template variables.",
    steps: ["Select a notification trigger/type and channel.", "Review the supported variable list, such as member.firstName, member.email, campaign.name, or points.", "Enter the subject/body for each supported locale.", "Save and review the preview, if available; confirm the template matches the customer's selected language."],
    result: "Triggered notifications use the configured content for the applicable locale and channel.",
    notes: ["Use only listed variables; unsupported names may render blank.", "Never include passwords, tokens, secret codes, or other sensitive information in a template."],
  },
  settings: {
    title: "Settings and Microsoft 365 sign-in", group: "Reporting and notifications",
    purpose: "Configure system options such as Microsoft 365 sign-in and administrative integration settings.",
    prerequisites: "You need settings-management permission. Tenant, client, scope, and callback values must come from your Microsoft 365/IT administrator.",
    steps: ["Open Settings and enable Microsoft sign-in only after confirming the tenant, client ID, scopes, and callback URL.", "Enter and verify configuration according to IT guidance; do not copy secrets from the browser or shared documents.", "Save, test with an authorized account, and verify admin approval if new admin accounts require approval.", "Record the change and responsible person according to your audit policy."],
    result: "Microsoft sign-in works only with valid tenant and callback configuration. Creating an admin account may still require approval from an existing administrator.",
    notes: ["Never record or screenshot secrets, client secrets, tokens, or recovery codes in Logs or documentation.", "An incorrect tenant or callback can block sign-in; keep an authorized backup administrator."],
  },
};
